### ISSUE TITLE
Presupposes jupyter notebook right now

### ISSUE THREAD

**Issue by jonbmartin** [ranabanik/MIS6020#2]
Could you give installation instructions for jupyter notebook in the readme.md?

**Comment by jonbmartin** [comment]
Or even better... just transition the instructions from a jupyter notebook to the readme.md? That would be the best thing.

**Comment by ranabanik** [comment]
They don’t need to install Jupiter notebook to read registration/Homework0.ipynb. 

For example, this image is from my phone: 

![IMG_9416](https://github.com/ranabanik/MIS6020/assets/47092529/626f6664-307e-4624-91cd-6c797b0f4f4d)

can you see it? I also verified by sending it to a workstation without any code/python/notebook. I can see the instructions fully. 
Are you having any visibility issue? Lmk

**Comment by jonbmartin** [comment]
ah right you are! very nice. Good to go.
